### ISSUE TITLE
`containerd` is killing static pods

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1737]
## Issue 

`containerd` is killing static pods (e.g. etcd) periodically when `containerd` is configured with registry credentials which causes the `etcd` cluster, the Kubernetes API, the `controller-manager` and the `scheduler` to fail often.

The cluster is stable after the registry credentials are removed.

The problem occurs on both public and private AWS clusters if `containerd` is configured with registry credentials.

## Questions

- Is the problem present on AWS vintage?
- Is the problem present on CAPVCD?

## Resources

- [Slack thread](https://gigantic.slack.com/archives/C04AJ5FJHEK/p1670004187637159).

**Comment by tuladhar** [comment]
I've applied the hot-fix and tested it on golem, and new workload cluster is created with registry auth config applied:
- https://github.com/giantswarm/cluster-aws/compare/master...bug-container-registry

Also, tested scaling the workload cluster.

**Comment by alex-dabija** [comment]
The `containerd` issue we've been facing when the registry authentication is enabled is probably a bug between the Linux kernel, systemd & containerd. We rolled back the OS to Ubuntu 20.04 and we were able to create a few clusters successfully.

**Comment by alex-dabija** [comment]
I think we should default to Ubuntu 20.04 in `cluster-aws` in order to unblock the creation of private clusters in a private environment.

**Comment by alex-dabija** [comment]
We are going remove the workaround which partially fixed the problem and drop back to using Ubuntu 20.04 instead of Ubuntu 22.04.

**Comment by calvix** [comment]
fixed in release https://github.com/giantswarm/cluster-aws/pull/187

**Comment by alex-dabija** [comment]
We have the workaround in place and we are going to investigate the issue with Ubuntu 22.04 when we have more time.

**Comment by alex-dabija** [comment]
The issue was encountered on 2 different providers, CAPA & CAPVCD, with Ubuntu 22.04. The issue is most probably common for all providers which use Ubuntu. Switching to Flatcar might fix the issue.

**Comment by primeroz** [comment]
this is still an issue even on flatcar: https://gigantic.slack.com/archives/C02HLSDH3DZ/p1686836442216509

**Comment by calvix** [comment]
We saw an issue where containers were killed on flatcar as well, but when moving the whole configuration into the root config file, the issue disappeared. 

Just to be clear  I moved the contents of `/etc/containerd/conf.d/registry-config.toml`  to the root config file `/etc/containerd/config.toml` and the issue was gone

**Comment by primeroz** [comment]
since the issue has been identified and the same fix is being applied to capz , can we close this issue ? 

vsphere and cloud-director don't have the issue since they are on ubuntu 20.04
